packages:
  - packages/*
  - tooling/*

catalog:
  typescript: ^5.6.3
  eslint: ^9.16.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.16

catalogs:
  react:
    react: 18.3.1
    react-dom: 19.0.0
    '@types/react': ^18.3.13
    '@types/react-dom': ^19.0.3
