name: '🏷️  '
author: 'PHILLIPS71'

inputs:
  GITHUB_TOKEN:
    required: true
  RELEASE_TYPE:
    required: true
  RELEASE_IDENTIFIER:
    required: false

outputs:
  version:
    value: ${{ steps.version.outputs.version }}
  branch:
    value: ${{ steps.branch.outputs.branch }}

runs:
  using: 'composite'
  steps:
    - name: '🏷️  Increment Release'
      id: version
      uses: giantnodes/next-semver@v1
      with:
        path: VERSION.txt
        type: ${{ inputs.RELEASE_TYPE }}
        identifier: ${{ inputs.RELEASE_IDENTIFIER }}

    - name: '🏷️  Version @giantnodes/design-system'
      shell: bash
      run: |
        pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version

    - name: '🏷️  Version @giantnodes/theme'
      working-directory: packages/theme
      shell: bash
      run: |
        pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version

    - name: '🏷️  Version @giantnodes/react'
      working-directory: packages/react
      shell: bash
      run: |
        pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version

    - name: '🏷️  Configure Git'
      shell: bash
      run: |
        git config --global user.name 'Giantnodes Bot'
        git config --global user.email 'bot@giantnodes.com'

    - name: '🏷️  Tag, Commit & Release'
      shell: bash
      id: branch
      run: |
        git checkout -b release/${{ steps.version.outputs.version }}
        git commit -anm 'chore(release): ${{ steps.version.outputs.version }}'
        git tag ${{ steps.version.outputs.version }}
        git push origin release/${{ steps.version.outputs.version }} --tags --force

        gh release create ${{ steps.version.outputs.version }} --generate-notes

        echo "branch=$(git branch --show-current)" >> $GITHUB_OUTPUT

    # - name: '🏷️  Open Pull Request'
    #   uses: thomaseizinger/create-pull-request@master
    #   with:
    #     title: 'chore(release): ${{ steps.version.outputs.version }}'
    #     labels: '🏷️ Release, 🥳️ LGTM'
    #     github_token: ${{ inputs.GITHUB_TOKEN }}
    #     head: release/${{ steps.version.outputs.version }}
    #     base: main
