name: main

on:
  push:
    branches: [main, next]
  pull_request:

jobs:
  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v3

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: install
        run: pnpm install

      - name: build
        run: pnpm run build

  typescript:
    name: 🦺 Type Check
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v3

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: install
        run: pnpm install

      - name: build
        run: pnpm build

      - name: type check
        run: pnpm run typecheck

  lint:
    name: 🚨 Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v3

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: install
        run: pnpm install

      - name: lint
        run: pnpm run lint

  test:
    name: 🧪 Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v3

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: install
        run: pnpm install

      - name: test
        run: pnpm run test
