name: '🏷️  Release'

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: 'SemVer Increment'
        default: 'prerelease'
        required: true
        options:
          - prerelease
          - prepatch
          - patch
          - preminor
          - minor
          - premajor
          - major
      identifier:
        type: choice
        description: 'Version Prefix'
        required: false
        options:
          - canary

jobs:
  release:
    name: '🏷️  Release'
    runs-on: ubuntu-latest
    steps:
      - name: '🐙️  Checkout'
        uses: actions/checkout@v4

      - name: '💽️  Init'
        uses: ./.github/actions/init

      - name: '🏷️  Release'
        uses: ./.github/actions/release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TYPE: ${{ github.event.inputs.type }}
          RELEASE_IDENTIFIER: ${{ github.event.inputs.identifier }}
