name: '🏷️  Release'

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: 'SemVer Increment'
        default: 'prerelease'
        required: true
        options:
          - prerelease
          - prepatch
          - patch
          - preminor
          - minor
          - premajor
          - major
      identifier:
        type: choice
        description: 'Version Prefix'
        default: ''
        options:
          - canary

jobs:
  create-release:
    name: '🏷️  Create Release'
    runs-on: ubuntu-latest
    steps:
      - name: '🐙️  Checkout'
        uses: actions/checkout@v4

      - name: '💽️  Init'
        uses: ./.github/actions/init

      - name: '🏷️  Release'
        id: release
        uses: ./.github/actions/release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TYPE: ${{ github.event.inputs.type }}
          RELEASE_IDENTIFIER: ${{ github.event.inputs.identifier }}
    outputs:
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag }}
      branch: ${{ steps.release.outputs.branch }}

  publish-theme:
    name: '🏷️  Publish @giantnodes/theme'
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - name: '🐙️  Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.create-release.outputs.branch }}

      - name: '💽️  Init'
        uses: ./.github/actions/init

      - name: '📦  Install'
        uses: ./.github/actions/install

      - name: '🔺️  Cache (turbo)'
        uses: ./.github/actions/cache

      - name: '🏗️  Build'
        uses: ./.github/actions/build
        with:
          COMMAND: 'build'

      - name: '🏷️  Publish @giantnodes/theme'
        working-directory: packages/theme
        shell: bash
        run: |
          pnpm publish --tag ${{ needs.create-release.outputs.tag }} --publish-branch ${{ needs.create-release.outputs.branch }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-react:
    name: '🏷️  Publish @giantnodes/react'
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - name: '🐙️  Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.create-release.outputs.branch }}

      - name: '💽️  Init'
        uses: ./.github/actions/init

      - name: '📦  Install'
        uses: ./.github/actions/install

      - name: '🔺️  Cache (turbo)'
        uses: ./.github/actions/cache

      - name: '🏗️  Build'
        uses: ./.github/actions/build
        with:
          COMMAND: 'build'

      - name: '🏷️  Publish @giantnodes/react'
        working-directory: packages/react
        shell: bash
        run: |
          pnpm publish --tag ${{ needs.create-release.outputs.tag }} --publish-branch ${{ needs.create-release.outputs.branch }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
